// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $cart from "./routes/cart.tsx";
import * as $checkout from "./routes/checkout.tsx";
import * as $film_id_ from "./routes/film/[id].tsx";
import * as $films from "./routes/films.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $products_product_ from "./routes/products/[product].tsx";
import * as $AddFilm from "./islands/AddFilm.tsx";
import * as $AddProduct from "./islands/AddProduct.tsx";
import * as $BrandHSelect from "./islands/BrandHSelect.tsx";
import * as $BrandSelect from "./islands/BrandSelect.tsx";
import * as $CartPrice from "./islands/CartPrice.tsx";
import * as $CheckOutButton from "./islands/CheckOutButton.tsx";
import * as $CitySelect from "./islands/CitySelect.tsx";
import * as $ColorHSelect from "./islands/ColorHSelect.tsx";
import * as $ColorSelect from "./islands/ColorSelect.tsx";
import * as $CountrySelect from "./islands/CountrySelect.tsx";
import * as $DecreaseProduct from "./islands/DecreaseProduct.tsx";
import * as $FilmCatalogue from "./islands/FilmCatalogue.tsx";
import * as $FilmModal from "./islands/FilmModal.tsx";
import * as $Filters from "./islands/Filters.tsx";
import * as $FormatHSelect from "./islands/FormatHSelect.tsx";
import * as $FormatSelect from "./islands/FormatSelect.tsx";
import * as $ISOHSelect from "./islands/ISOHSelect.tsx";
import * as $ISOSelect from "./islands/ISOSelect.tsx";
import * as $NewProjectModal from "./islands/NewProjectModal.tsx";
import * as $NumCarrito from "./islands/NumCarrito.tsx";
import * as $ProjectsModal from "./islands/ProjectsModal.tsx";
import * as $SearchBar from "./islands/SearchBar.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/cart.tsx": $cart,
    "./routes/checkout.tsx": $checkout,
    "./routes/film/[id].tsx": $film_id_,
    "./routes/films.tsx": $films,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/products/[product].tsx": $products_product_,
  },
  islands: {
    "./islands/AddFilm.tsx": $AddFilm,
    "./islands/AddProduct.tsx": $AddProduct,
    "./islands/BrandHSelect.tsx": $BrandHSelect,
    "./islands/BrandSelect.tsx": $BrandSelect,
    "./islands/CartPrice.tsx": $CartPrice,
    "./islands/CheckOutButton.tsx": $CheckOutButton,
    "./islands/CitySelect.tsx": $CitySelect,
    "./islands/ColorHSelect.tsx": $ColorHSelect,
    "./islands/ColorSelect.tsx": $ColorSelect,
    "./islands/CountrySelect.tsx": $CountrySelect,
    "./islands/DecreaseProduct.tsx": $DecreaseProduct,
    "./islands/FilmCatalogue.tsx": $FilmCatalogue,
    "./islands/FilmModal.tsx": $FilmModal,
    "./islands/Filters.tsx": $Filters,
    "./islands/FormatHSelect.tsx": $FormatHSelect,
    "./islands/FormatSelect.tsx": $FormatSelect,
    "./islands/ISOHSelect.tsx": $ISOHSelect,
    "./islands/ISOSelect.tsx": $ISOSelect,
    "./islands/NewProjectModal.tsx": $NewProjectModal,
    "./islands/NumCarrito.tsx": $NumCarrito,
    "./islands/ProjectsModal.tsx": $ProjectsModal,
    "./islands/SearchBar.tsx": $SearchBar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
