// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $film_id_ from "./routes/film/[id].tsx";
import * as $films from "./routes/films.tsx";
import * as $index from "./routes/index.tsx";
import * as $projects from "./routes/projects.tsx";
import * as $FilmCatalogue from "./islands/FilmCatalogue.tsx";
import * as $FilmModal from "./islands/FilmModal.tsx";
import * as $Filters from "./islands/Filters.tsx";
import * as $NewProjectModal from "./islands/NewProjectModal.tsx";
import * as $ProjectsModal from "./islands/ProjectsModal.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/film/[id].tsx": $film_id_,
    "./routes/films.tsx": $films,
    "./routes/index.tsx": $index,
    "./routes/projects.tsx": $projects,
  },
  islands: {
    "./islands/FilmCatalogue.tsx": $FilmCatalogue,
    "./islands/FilmModal.tsx": $FilmModal,
    "./islands/Filters.tsx": $Filters,
    "./islands/NewProjectModal.tsx": $NewProjectModal,
    "./islands/ProjectsModal.tsx": $ProjectsModal,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
